import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Counter } from "@/components";
import { ExampleComponent } from "@/components/ExampleComponent";
import { RandomImageFetching } from "@/components/RandomImageFetching/RandomImageFetching";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Testing Initialized</h1>
        {/* <Counter defaultValue={0} header="Welcome to this Awesome Counter!" />
        <ExampleComponent
          onMoney={(n: number) => {
            console.log(n);
          }}
        /> */}
        <RandomImageFetching />
      </main>
    </>
  );
}
